version: "0.0"
services:
  notebook:
  #jupyter notebook server
    build: .
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
    ports:
      - "8888:8888"
    volumes:
      - ./:/code
      - ./data:/code/data
    entrypoint:
      [
        "jupyter",
        "notebook",
        "--port=8888",
        "--no-browser",
        "--ip=0.0.0.0",
        "--allow-root",
        "--NotebookApp.token=''",
        "--NotebookApp.password=''"
      ]
  prefect:
  # prefect orchestration server
    build: .
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
    ports:
      - "4200:4200"
    entrypoint: [ "prefect", "orion", "start" ]
